
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Fri Nov 29 11:28:14 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5911
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/beresnev28/.Xresources'
/usr/bin/startxfce4: X server already running on display :11
gpg-agent[1447]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:1440): xfce4-session-WARNING **: 11:28:17.579: gpg-agent returned no PID in the variables

(xfce4-session:1440): xfce4-session-WARNING **: 11:28:17.580: xfsm_manager_load_session: Something wrong with /home/is28/beresnev28/.cache/sessions/xfce4-session-virt-1:11, Does it exist? Permissions issue?

(xfwm4:1450): xfwm4-WARNING **: 11:28:17.613: The display does not support the XRender extension.

(xfwm4:1450): xfwm4-WARNING **: 11:28:17.613: The display does not support the XComposite extension.

(xfwm4:1450): xfwm4-WARNING **: 11:28:17.613: The display does not support the XDamage extension.

(xfwm4:1450): xfwm4-WARNING **: 11:28:17.613: The display does not support the XFixes extension.

(xfwm4:1450): xfwm4-WARNING **: 11:28:17.613: Compositing manager disabled.

(polkit-gnome-authentication-agent-1:1462): GLib-CRITICAL **: 11:28:17.637: g_variant_new_string: assertion 'string != NULL' failed

** (light-locker:1460): ERROR **: 11:28:17.639: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:1462): polkit-gnome-1-WARNING **: 11:28:17.643: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(uint32 2,)
xfwm4-Message: 11:28:17.680: Unsupported keyboard modifier '<Super>Tab'

(xfsettingsd:1464): xfsettingsd-CRITICAL **: 11:28:17.746: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":11.0".

(xfsettingsd:1464): xfsettingsd-CRITICAL **: 11:28:17.746: XI is not present.

(xfsettingsd:1464): xfsettingsd-CRITICAL **: 11:28:17.747: Failed to initialize the Xkb extension.

(xfsettingsd:1464): xfsettingsd-CRITICAL **: 11:28:17.747: Failed to initialize the Accessibility extension.

(tracker-miner-apps:1515): Tracker-CRITICAL **: 11:28:17.824: Could not request DBus name 'org.freedesktop.Tracker1.Miner.Applications': D-Bus service name:'org.freedesktop.Tracker1.Miner.Applications' is already taken, perhaps the application is already running?
xfwm4-Message: 11:28:17.827: Unsupported keyboard modifier '<Super>Tab'

(tracker-extract:1481): Tracker-CRITICAL **: 11:28:17.879: Could not request DBus name 'org.freedesktop.Tracker1.Miner.Extract': D-Bus service name:'org.freedesktop.Tracker1.Miner.Extract' is already taken, perhaps the application is already running?

(nm-applet:1522): Gtk-WARNING **: 11:28:17.937: Can't set a parent on widget which has a parent

(tracker-miner-fs:1465): Tracker-CRITICAL **: 11:28:17.957: Could not request DBus name 'org.freedesktop.Tracker1.Miner.Files': D-Bus service name:'org.freedesktop.Tracker1.Miner.Files' is already taken, perhaps the application is already running?

(nm-applet:1522): Gdk-CRITICAL **: 11:28:18.077: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Fri Nov 29 11:28:26 2019
 Connections: accepted: 0.0.0.0::50315
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Fri Nov 29 11:28:30 2019
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.6901" (uid=1266 pid=1516 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.6901" (uid=1266 pid=1516 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.6901" (uid=1266 pid=1516 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(wrapper-1.0:1564): Gdk-WARNING **: 11:28:43.275: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(wrapper-1.0:1564): Gdk-WARNING **: 11:28:43.275: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(Thunar:1456): Gdk-WARNING **: 11:29:19.711: gdk_window_set_icon_list: icons too large
Xlib:  extension "XINERAMA" missing on display ":11.0".
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

(soffice:9893): GLib-GObject-WARNING **: 11:29:26.113: ../../../../gobject/gsignal.c:3492: signal name 'selection_changed' is invalid for instance '0x55f39ced46a0' of type 'OOoAtkObjCompTxt'

(Thunar:1456): Gdk-WARNING **: 11:32:04.629: gdk_window_set_icon_list: icons too large
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

Fri Nov 29 12:31:07 2019
 Connections: closed: 0.0.0.0::50315 (read: Connection reset by peer (104))
 SMsgWriter:  framebuffer updates 9438
 SMsgWriter:    copyRect rects 9793, bytes 156688
 SMsgWriter:    hextile rects 37773, bytes 89006831
 SMsgWriter:    raw bytes equivalent 783406548, compression ratio 8.801645
xfce4-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.
xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

(xfce4-panel:1454): libxfce4ui-WARNING **: 11:32:29.290: ICE I/O Error

(xfce4-panel:1454): libxfce4ui-WARNING **: 11:32:29.290: Disconnected from session manager.

(xfsettingsd:1464): libxfce4ui-WARNING **: 11:32:29.291: ICE I/O Error

(xfsettingsd:1464): libxfce4ui-WARNING **: 11:32:29.291: Disconnected from session manager.

(x-terminal-emulator:4325): libxfce4ui-WARNING **: 11:32:29.292: ICE I/O Error

(x-terminal-emulator:4325): libxfce4ui-WARNING **: 11:32:29.292: Disconnected from session manager.

(xfdesktop:1459): libxfce4ui-WARNING **: 11:32:29.312: ICE I/O Error

(xfdesktop:1459): libxfce4ui-WARNING **: 11:32:29.312: Disconnected from session manager.
Thunar: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.
xfce4-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.
Gdk-Message: 11:32:29.330: polkit-gnome-authentication-agent-1: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.
wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.
Gdk-Message: 11:32:29.503: update-notifier: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

Gdk-Message: 11:32:29.510: evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.
Gdk-Message: 11:32:29.512: blueman-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

Gdk-Message: 11:32:29.515: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

Gdk-Message: 11:32:29.516: x-terminal-emulator: Fatal IO error 11 (Resource temporarily unavailable) on X server :11.0.

X IO Error
/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.6899" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 11 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 15 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 16 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 20 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 24 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 26 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 28 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 30 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 34 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 36 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 40 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 41 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 45 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 47 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 49 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 53 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 55 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 59 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 60 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 64 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 66 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 67 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 71 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 73 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 74 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 78 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 80 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 82 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 86 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 87 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 91 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 93 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 94 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 98 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 100 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 101 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 102 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 103 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 104 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 106 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 108 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 110 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 111 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 115 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 117 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 118 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 122 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 124 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 126 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 130 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 132 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 138 was not found when attempting to remove it
  GLib.source_remove (self.timer)
