
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Fri Nov 29 11:25:31 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5934
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/zavadskaya28/.Xresources'
/usr/bin/startxfce4: X server already running on display :34
gpg-agent[62414]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:62404): xfce4-session-WARNING **: 11:25:34.873: gpg-agent returned no PID in the variables

(xfce4-session:62404): xfce4-session-WARNING **: 11:25:34.877: xfsm_manager_load_session: Something wrong with /home/is28/zavadskaya28/.cache/sessions/xfce4-session-virt-1:34, Does it exist? Permissions issue?

(xfwm4:62418): xfwm4-WARNING **: 11:25:34.901: The display does not support the XRender extension.

(xfwm4:62418): xfwm4-WARNING **: 11:25:34.901: The display does not support the XComposite extension.

(xfwm4:62418): xfwm4-WARNING **: 11:25:34.901: The display does not support the XDamage extension.

(xfwm4:62418): xfwm4-WARNING **: 11:25:34.901: The display does not support the XFixes extension.

(xfwm4:62418): xfwm4-WARNING **: 11:25:34.901: Compositing manager disabled.
(uint32 1,)

** (light-locker:62427): ERROR **: 11:25:34.949: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:62430): GLib-CRITICAL **: 11:25:34.983: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:62430): polkit-gnome-1-WARNING **: 11:25:34.984: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
xfwm4-Message: 11:25:35.023: Unsupported keyboard modifier '<Super>Tab'

(xfsettingsd:62429): xfsettingsd-CRITICAL **: 11:25:35.050: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":34.0".

(xfsettingsd:62429): xfsettingsd-CRITICAL **: 11:25:35.050: XI is not present.

(xfsettingsd:62429): xfsettingsd-CRITICAL **: 11:25:35.054: Failed to initialize the Xkb extension.

(xfsettingsd:62429): xfsettingsd-CRITICAL **: 11:25:35.054: Failed to initialize the Accessibility extension.
xfwm4-Message: 11:25:35.110: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:62535): Gtk-WARNING **: 11:25:35.450: Can't set a parent on widget which has a parent

(nm-applet:62535): Gdk-CRITICAL **: 11:25:35.599: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.5446" (uid=1272 pid=62516 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.5446" (uid=1272 pid=62516 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.5446" (uid=1272 pid=62516 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(wrapper-1.0:62576): Gdk-WARNING **: 11:26:00.635: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

Fri Nov 29 11:26:24 2019
 Connections: accepted: 0.0.0.0::50209
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Fri Nov 29 11:26:28 2019
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565

(Thunar:62424): Gdk-WARNING **: 11:27:21.060: gdk_window_set_icon_list: icons too large
xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
xfce4-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.

(xfdesktop:62426): libxfce4ui-WARNING **: 11:27:39.291: ICE I/O Error

(xfdesktop:62426): libxfce4ui-WARNING **: 11:27:39.291: Disconnected from session manager.

(xfce4-panel:62422): libxfce4ui-WARNING **: 11:27:39.291: ICE I/O Error

(xfce4-panel:62422): libxfce4ui-WARNING **: 11:27:39.291: Disconnected from session manager.

(xfsettingsd:62429): libxfce4ui-WARNING **: 11:27:39.291: ICE I/O Error

(xfsettingsd:62429): libxfce4ui-WARNING **: 11:27:39.291: Disconnected from session manager.
xfce4-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
Thunar: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
Gdk-Message: 11:27:39.299: polkit-gnome-authentication-agent-1: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.

Gdk-Message: 11:27:39.299: blueman-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.

wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.
Gdk-Message: 11:27:39.299: update-notifier: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.

Gdk-Message: 11:27:39.299: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.

Gdk-Message: 11:27:39.303: evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :34.0.


(tracker-miner-fs:62432): Tracker-CRITICAL **: 11:59:37.348:   (Sparql buffer) Error in task 0 (file:///home/is28/zavadskaya28/01.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:62432): Tracker-CRITICAL **: 11:59:37.348: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:62432): Tracker-CRITICAL **: 12:07:35.491:   (Sparql buffer) Error in task 0 (file:///home/is28/zavadskaya28/01.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:62432): Tracker-CRITICAL **: 12:07:35.491: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:62432): Tracker-CRITICAL **: 12:08:29.895:   (Sparql buffer) Error in task 0 (file:///home/is28/zavadskaya28/01.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:62432): Tracker-CRITICAL **: 12:08:29.895: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url
/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.5443" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 11 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 15 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 16 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 20 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 24 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 26 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 28 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 30 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 34 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 36 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 40 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 41 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 45 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 47 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 49 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 53 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 55 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 59 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 60 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 64 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 66 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 67 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 71 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 73 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 74 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 78 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 80 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 82 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 86 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 87 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 91 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 93 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 94 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 98 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 100 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 101 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 102 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 103 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 104 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 106 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 108 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 110 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 111 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 115 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 117 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 118 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 122 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 124 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 126 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 130 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 132 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 138 was not found when attempting to remove it
  GLib.source_remove (self.timer)
