
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Thu Feb  6 09:35:34 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5913
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/sharutin28/.Xresources'
/usr/bin/startxfce4: X server already running on display :13
gpg-agent[48971]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:48961): xfce4-session-WARNING **: 09:35:38.108: gpg-agent returned no PID in the variables

(xfce4-session:48961): xfce4-session-WARNING **: 09:35:38.196: xfsm_manager_load_session: Something wrong with /home/is28/sharutin28/.cache/sessions/xfce4-session-virt-1:13, Does it exist? Permissions issue?

(xfwm4:48975): xfwm4-WARNING **: 09:35:38.224: The display does not support the XRender extension.

(xfwm4:48975): xfwm4-WARNING **: 09:35:38.224: The display does not support the XComposite extension.

(xfwm4:48975): xfwm4-WARNING **: 09:35:38.224: The display does not support the XDamage extension.

(xfwm4:48975): xfwm4-WARNING **: 09:35:38.224: The display does not support the XFixes extension.

(xfwm4:48975): xfwm4-WARNING **: 09:35:38.224: Compositing manager disabled.
(uint32 1,)

** (light-locker:48984): ERROR **: 09:35:38.264: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:48987): GLib-CRITICAL **: 09:35:38.298: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:48987): polkit-gnome-1-WARNING **: 09:35:38.301: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
xfwm4-Message: 09:35:38.345: Unsupported keyboard modifier '<Super>Tab'

(xfsettingsd:48986): xfsettingsd-CRITICAL **: 09:35:38.352: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":13.0".

(xfsettingsd:48986): xfsettingsd-CRITICAL **: 09:35:38.354: XI is not present.

(xfsettingsd:48986): xfsettingsd-CRITICAL **: 09:35:38.355: Failed to initialize the Xkb extension.

(xfsettingsd:48986): xfsettingsd-CRITICAL **: 09:35:38.355: Failed to initialize the Accessibility extension.
xfwm4-Message: 09:35:38.429: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:49090): Gtk-WARNING **: 09:35:38.663: Can't set a parent on widget which has a parent

(nm-applet:49090): Gdk-CRITICAL **: 09:35:38.816: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Thu Feb  6 09:35:55 2020
 Connections: accepted: 0.0.0.0::49683
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
/usr/lib/ubuntu-release-upgrader/check-new-release-gtk:30: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING:root:timeout reached, exiting

Thu Feb  6 09:36:01 2020
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.741" (uid=1288 pid=49059 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.741" (uid=1288 pid=49059 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.741" (uid=1288 pid=49059 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(polkit-gnome-authentication-agent-1:48987): polkit-gnome-1-WARNING **: 09:43:39.266: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:48987): polkit-gnome-1-WARNING **: 09:43:39.267: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 09:43:39.297: GtkDialog mapped without a transient parent. This is discouraged.

(Thunar:48981): GLib-GIO-CRITICAL **: 09:43:40.997: g_file_hash: assertion 'G_IS_FILE (file)' failed

(Thunar:48981): GLib-GIO-CRITICAL **: 09:43:40.997: g_file_query_info_async: assertion 'G_IS_FILE (file)' failed

(Thunar:48981): GLib-GObject-CRITICAL **: 09:43:40.997: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(polkit-gnome-authentication-agent-1:48987): polkit-gnome-1-WARNING **: 09:44:34.773: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:48987): polkit-gnome-1-WARNING **: 09:44:34.774: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 09:44:34.780: GtkDialog mapped without a transient parent. This is discouraged.

(Thunar:48981): Gdk-WARNING **: 09:44:35.213: gdk_window_set_icon_list: icons too large

(Thunar:48981): GLib-GIO-CRITICAL **: 09:44:36.807: g_file_hash: assertion 'G_IS_FILE (file)' failed

(Thunar:48981): GLib-GIO-CRITICAL **: 09:44:36.808: g_file_query_info_async: assertion 'G_IS_FILE (file)' failed

(Thunar:48981): GLib-GObject-CRITICAL **: 09:44:36.808: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(Thunar:48981): Gdk-WARNING **: 09:56:19.790: gdk_window_set_icon_list: icons too large

(Thunar:48981): Gdk-WARNING **: 09:56:49.005: gdk_window_set_icon_list: icons too large

Thu Feb  6 10:02:31 2020
 Connections: closed: 0.0.0.0::49683 (Clean disconnection)
 SMsgWriter:  framebuffer updates 14182
 SMsgWriter:    copyRect rects 5956, bytes 95296
 SMsgWriter:    hextile rects 52537, bytes 65111022
 SMsgWriter:    raw bytes equivalent 550804682, compression ratio 8.459469

Thu Feb  6 10:02:35 2020
 Connections: accepted: 0.0.0.0::49856
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Thu Feb  6 10:02:38 2020
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565

Thu Feb  6 10:02:58 2020
 Connections: closed: 0.0.0.0::49856 (Clean disconnection)
 SMsgWriter:  framebuffer updates 248
 SMsgWriter:    hextile rects 1588, bytes 204887
 SMsgWriter:    raw bytes equivalent 6503434, compression ratio 31.741565

** (xfdesktop:48983): WARNING **: 20:30:13.059: Attempt to remove icon 0x5588bc49c770 from XfdesktopIconView 0x5588bc49c190, but it's not in there.
/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.738" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 10 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 14 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 16 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 17 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 21 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 23 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 24 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 28 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 30 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 31 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 35 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 37 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 38 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 42 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 44 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 45 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 49 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 51 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 52 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 56 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 58 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 59 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 63 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 65 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 66 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 70 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 72 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 73 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 77 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 79 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 80 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 84 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 86 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 87 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 91 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 93 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 94 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 98 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 100 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 101 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 105 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 106 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 108 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 109 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 113 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 115 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 117 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 118 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 122 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 124 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 125 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 129 was not found when attempting to remove it
  GLib.source_remove (self.timer)

(xfdesktop:48983): libxfce4ui-WARNING **: 09:42:54.935: ICE I/O Error

(xfdesktop:48983): libxfce4ui-WARNING **: 09:42:55.015: Disconnected from session manager.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.0.
xfwm4: Fatal IO error 4 (Interrupted system call) on X server :13.0.
