
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Thu Mar 12 09:49:50 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5916
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/sharutin28/.Xresources'
/usr/bin/startxfce4: X server already running on display :16
gpg-agent[11514]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:11504): xfce4-session-WARNING **: 09:49:53.993: gpg-agent returned no PID in the variables

(xfce4-session:11504): xfce4-session-WARNING **: 09:49:53.999: xfsm_manager_load_session: Something wrong with /home/is28/sharutin28/.cache/sessions/xfce4-session-virt-1:16, Does it exist? Permissions issue?

(xfwm4:11518): xfwm4-WARNING **: 09:49:54.035: The display does not support the XRender extension.

(xfwm4:11518): xfwm4-WARNING **: 09:49:54.035: The display does not support the XComposite extension.

(xfwm4:11518): xfwm4-WARNING **: 09:49:54.035: The display does not support the XDamage extension.

(xfwm4:11518): xfwm4-WARNING **: 09:49:54.035: The display does not support the XFixes extension.

(xfwm4:11518): xfwm4-WARNING **: 09:49:54.035: Compositing manager disabled.

** (light-locker:11527): ERROR **: 09:49:54.058: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:11529): GLib-CRITICAL **: 09:49:54.084: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:11529): polkit-gnome-1-WARNING **: 09:49:54.090: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(uint32 1,)

(xfsettingsd:11531): xfsettingsd-CRITICAL **: 09:49:54.113: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":16.0".

(xfsettingsd:11531): xfsettingsd-CRITICAL **: 09:49:54.115: XI is not present.

(xfsettingsd:11531): xfsettingsd-CRITICAL **: 09:49:54.120: Failed to initialize the Xkb extension.

(xfsettingsd:11531): xfsettingsd-CRITICAL **: 09:49:54.120: Failed to initialize the Accessibility extension.
xfwm4-Message: 09:49:54.144: Unsupported keyboard modifier '<Super>Tab'
xfwm4-Message: 09:49:54.249: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:11598): Gtk-WARNING **: 09:49:54.513: Can't set a parent on widget which has a parent

(nm-applet:11598): Gdk-CRITICAL **: 09:49:54.653: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Thu Mar 12 09:50:11 2020
 Connections: accepted: 0.0.0.0::49321
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Thu Mar 12 09:50:15 2020
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/ubuntu-release-upgrader/check-new-release-gtk:30: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING:root:timeout reached, exiting
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.576" (uid=1288 pid=11581 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.576" (uid=1288 pid=11581 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.576" (uid=1288 pid=11581 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(wrapper-1.0:11673): Gdk-WARNING **: 09:50:19.575: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(wrapper-1.0:11673): Gdk-WARNING **: 09:50:19.575: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(medit:12449): GLib-GObject-CRITICAL **: 09:56:03.169: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(gedit:12930): Gtk-WARNING **: 09:58:57.157: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist


(polkit-gnome-authentication-agent-1:11529): polkit-gnome-1-WARNING **: 10:17:22.296: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:11529): polkit-gnome-1-WARNING **: 10:17:22.308: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 10:17:22.335: GtkDialog mapped without a transient parent. This is discouraged.
Error: GDBus.Error:org.freedesktop.DBus.Error.AuthFailed: Not authorized.
Gtk-Message: 10:17:25.174: GtkDialog mapped without a transient parent. This is discouraged.
ERROR: hook /usr/share/apport/package-hooks/source_cheese.py crashed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 198, in _run_hook
    symb['add_info'](report, ui)
  File "/usr/share/apport/package-hooks/source_cheese.py", line 12, in add_info
    response = ui.information("Before continuing, please close Cheese if it is already running!\n\nCheese will now be started in debugging mode.\n\nTry to reproduce the problem you are facing\nand 'Close' Cheese.")
AttributeError: 'NoneType' object has no attribute 'information'

Thu Mar 12 10:58:25 2020
 Connections: closed: 0.0.0.0::49321 (Clean disconnection)
 SMsgWriter:  framebuffer updates 12795
 SMsgWriter:    copyRect rects 2253, bytes 36048
 SMsgWriter:    hextile rects 36278, bytes 86182002
 SMsgWriter:    raw bytes equivalent 809959860, compression ratio 9.398248
cat: /home/is28/sharutin28/.Xauthority: No such file or directory
AUDIT: Tue Mar 17 21:58:48 2020: 11482 Xvnc4: client 8 rejected from local host

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:25.704:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.00R1H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:25.704:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.T2R1H0”: No such file or directory

(Thunar:11524): thunar-WARNING **: 22:01:25.772: Failed to create bookmarks folder: Error creating directory /home/is28: Permission denied

(Thunar:11524): GLib-CRITICAL **: 22:01:25.772: g_file_set_contents: assertion 'error == NULL || *error == NULL' failed

(Thunar:11524): thunar-WARNING **: 22:01:25.772: Failed to write "/home/is28/sharutin28/.config/gtk-3.0/bookmarks": (null)

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:25.898:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.XD82H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:25.898:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.LF82H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:26.091:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.EM4LH0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:26.091:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.P23LH0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:26.113:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.6YBMH0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:26.113:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.RVBMH0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:26.115:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.GMNMH0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:01:26.115:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.91MMH0”: No such file or directory
AUDIT: Tue Mar 17 22:01:54 2020: 11482 Xvnc4: client 4 rejected from local host
No protocol specified
Unable to init server: Could not connect: Connection refused
AUDIT: Tue Mar 17 22:01:54 2020: 11482 Xvnc4: client 4 rejected from local host
No protocol specified
Unable to init server: Could not connect: Connection refused

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.900:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.NW62H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.900:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.ZX62H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.905:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.OEF3H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.905:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.WFF3H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.950:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.4F16H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.950:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.LH16H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.953:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.JDB7H0”: No such file or directory

(tracker-miner-fs:11532): Tracker-WARNING **: 22:03:29.953:   Could not create file:'/home/is28/sharutin28/.cache/tracker/last-crawl.txt' failed, Failed to create file “/home/is28/sharutin28/.cache/tracker/last-crawl.txt.NEB7H0”: No such file or directory
